# Copyright 2021 Jon Seager
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  redirect-map:
    default: "https://jnsgr.uk/demo-routes"
    description: A URL pointing to a list of redirects for Gosherve.
    type: string
